ReservasWeb/Controllers/ChannelManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ReservasWeb.ViewModels;
using ReservasWeb.ViewModels.Channel;
using ReservasWeb.Services;
using ReservasWeb.WebServices;
using ReservasWeb.Models;
using ReservasWeb.Utils;
using ReservasWeb.Authorize;
using System.Configuration;

namespace ReservasWeb.Controllers
{
    public class ChannelManagerController : BaseController
    {
        // GET: ChannelManager
        [RequiereLogin]
        public ActionResult Index()
        {
            ChannelViewModel vm = new ChannelViewModel();
            
            ChannelManagerService sv = new ChannelManagerService(this.db);
            Sesion sesion = System.Web.HttpContext.Current.Session["SesionUsuario"] as Sesion;//trae la sesion actual

            vm.idEstado = sv.estaLinkeadoHotel(sesion.idAlojamientoActual);
            vm.texto = Utils.ComboHelper.getLinkHotel(vm.idEstado);
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult getHotels()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_getHotels"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult getRates()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_getRates"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult downloadReservations()
        {
            string xml = ""; 
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_downloadReservations"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult getRooms()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_getRooms"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }



        [RequiereLogin]
        public ActionResult Modify()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_modify"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult Reservations()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_reservations"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            ChannelWebService sv = new ChannelWebService(this.db);
            sv.getReservations();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult View0()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_view"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        [RequiereLogin]
        public ActionResult getPortals()
        {
            string xml = "";
            xml = System.IO.File.ReadAllText(System.Web.HttpContext.Current.Server.MapPath(ConfigurationManager.AppSettings["RoomCloud_getPortals"]));
            xml = xml.Replace("##TOCKEN##", ConfigurationManager.AppSettings["RoomCloud_API_KEY"]);
            xml = xml.Replace("##USUARIO##", ConfigurationManager.AppSettings["RoomCloud_USER"]);
            xml = xml.Replace("##CLAVE##", ConfigurationManager.AppSettings["RoomCloud_PASS"]);
            string Resultado = ChannelWebService.postXMLData(ConfigurationManager.AppSettings["RoomCloud_URL_PROD"], xml);
            ChannelViewModel vm = new ChannelViewModel();
            vm.texto = Resultado;
            return View(vm);
        }

        // GET: ChannelManager/Details/5
        
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ChannelManager/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChannelManager/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public JsonResult ActivarLink(int id, bool disponible)
        {
            string resultado = "error";
            try
            {
                TiposHabitacionService tipoHabService = new TiposHabitacionService(this.db);
                tipoHabService.activarLink(id, disponible);
                resultado = "ok";
                
            }
            catch (Exception e)
            {
                Console.Write(e.Message);
            }
            return Json(new { Resultado = resultado });
        }

        // GET: ChannelManager/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ChannelManager/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChannelManager/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ChannelManager/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult TipoHabitaciones()
        {

ReservasWeb/Views/ChannelManager/Hoteles.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel
<style>
    .celD
    {
        border: 1px solid;
    }
    .celH{
        border: 1px solid;
    }
</style>

<div class="BarraAdmTopFlotante">
    <div class="container">
        <div class="barraMensajes">
            <span class="MensajeProcesando" id="Procesando" style="display:none;">Procesando...</span>

                  <input type="submit" value="Guardar Cambios" class="btn btn-success btnFrmGeneral" onclick="validarUpload();" />
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12">Hoteles</div>
        <hr />
        <div class="col-md-2">ID</div>
        <div class="col-md-2">Descripcion</div>
        <div class="col-md-2">Tarifas</div>
        <div class="col-md-2">Habitaciones</div>
        <div class="col-md-2">Reservas</div>
        <div class="col-md-2">Portales</div>
        <hr />
        <div class="" >
            <div class="col-md-2 celD">3677</div>
            <div class="col-md-2 celD">testReservasTravel</div>
            <div class="col-md-2 celD">@Html.ActionLink("Tarifas", "Tarifas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Habitaciones", "TipoHabitaciones")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Reservas", "Reservas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Portales", "Portales")</div>
        </div>
        <div class="">
            <div class="col-md-2 celD">Not Found</div>
            <div class="col-md-2 celD">----</div>
            <div class="col-md-2 celD">@Html.ActionLink("Tarifas", "Tarifas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Habitaciones", "Habitaciones")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Reservas", "Reservas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Portales", "Portales")</div>
        </div>
        <div class="">
            <div class="col-md-2 celD">Not Found</div>
            <div class="col-md-2 celD">----</div>
            <div class="col-md-2 celD">@Html.ActionLink("Tarifas", "Tarifas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Habitaciones", "Habitaciones")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Reservas", "Reservas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Portales", "Portales")</div>
        </div>
        <div class="">
            <div class="col-md-2 celD">Not Found</div>
            <div class="col-md-2 celD">----</div>
            <div class="col-md-2 celD">@Html.ActionLink("Tarifas", "Tarifas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Habitaciones", "Habitaciones")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Reservas", "Reservas")</div>
            <div class="col-md-2 celD">@Html.ActionLink("Portales", "Portales")</div>
        </div>
    </div>
    <div>
        Connect..1
        @Html.TextAreaFor(model => model.texto, 7, 63, new { @title = "Texto", @class = "form-control textarea-wide" })
    </div>
</div>

ReservasWeb/Views/ChannelManager/Index.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel

<!DOCTYPE html>
@{ 

}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    
</head>
<body>
    <div class="container">
    <div class="row">
        
        <div class="col-md-12"><h1>Channel Manager</h1></div>
        <div class="col-md-4"></div>
        <div class="col-md-4">Estado: @Model.texto</div>
        <div class="col-md-4"></div>
        <br />
        <p></p>
        <div class="col-md-12"><h4>Panel de Control</h4></div>
        @{
            if (Model.idEstado == 0)
            {
                <div class="col-md-3">
                    @Html.ActionLink("Iniciar Configuración", "elegirTiposHabitaciones")
                </div>
                <div class="col-md-3">
                    Modificar Configuración
                </div>
                <div class="col-md-3">
                    Activar 
                </div>
                <div class="col-md-3">
                    Desactivar
                </div>
            }
            else
            {
                @Html.ActionLink("Borrar Configuración", "BorrarConfiguracion")
                @Html.ActionLink("Modificar Configuracion", "ModificacionConfiguracion") 
                @Html.ActionLink("Activar", "ActivarChannel") 
                @Html.ActionLink("Desactivar", "Desactivar")
                }
            }
    </div>
</div>
</body>
</html>

ReservasWeb/Views/ChannelManager/Linkear.cshtml
@model ReservasWeb.ViewModels.EdicionTipoHabitacionViewModel


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Linkear</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>TiposHabitacione</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.idTipoHabitacion)
    
            <div class="form-group">
                ID HABITACION EXTERNA
               @Html.LabelFor(model => model.idTipoHabitacion, "idTipoHabitacion", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.idTipoHabitacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.idTipoHabitacion, "", new { @class = "text-danger" })
                </div>
            </div>
    
    
            <div class="form-group">
                @Html.LabelFor(model => model.nombreEs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombreEs, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombreEs, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.plazas, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.plazas, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.plazas, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.camaMatrimonial, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.camaMatrimonial, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.camaMatrimonial, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.camasSimples, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.camasSimples, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.camasSimples, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.horaCheckOutTardio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.horaCheckOutTardio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.horaCheckOutTardio, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.camasAdicionales, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.camasAdicionales, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.camasAdicionales, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.descripcionEs, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcionEs, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcionEs, "", new { @class = "text-danger" })
                </div>
            </div>
   
    
            <div class="form-group">
                @Html.LabelFor(model => model.permiteAdicionalCunasBebes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.permiteAdicionalCunasBebes)
                        @Html.ValidationMessageFor(model => model.permiteAdicionalCunasBebes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.permiteAdicionalMenores, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.permiteAdicionalMenores)
                        @Html.ValidationMessageFor(model => model.permiteAdicionalMenores, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.permiteAdicionalAdultos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.permiteAdicionalAdultos)
                        @Html.ValidationMessageFor(model => model.permiteAdicionalAdultos, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.compartida, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.compartida)
                        @Html.ValidationMessageFor(model => model.compartida, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.nombreEn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombreEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombreEn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.nombrePt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombrePt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombrePt, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.descripcionEn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcionEn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcionEn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.descripcionPt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcionPt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcionPt, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ReservasWeb/Views/ChannelManager/Modify.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel

<!DOCTYPE html>
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
    <div>
        Connect..1
        @Html.TextAreaFor(model => model.texto, 7, 63, new { @title = "Texto", @class = "form-control textarea-wide" })
    </div>
</body>
</html>

ReservasWeb/Views/ChannelManager/Reservations.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel

<!DOCTYPE html>
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
    <div>
        Connect..1
        @Html.TextAreaFor(model => model.texto, 7, 63, new { @title = "Texto", @class = "form-control textarea-wide" })
    </div>
</body>
</html>

ReservasWeb/Views/ChannelManager/Tarifas.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel
<style>
    .celD {
        border: 1px solid;
    }

    .celH {
        border: 1px solid;
    }
</style>

<div class="BarraAdmTopFlotante">
    <div class="container">
        <div class="barraMensajes">
            <span class="MensajeProcesando" id="Procesando" style="display:none;">Procesando...</span>
            5
            <input type="submit" value="Guardar Cambios" class="btn btn-success btnFrmGeneral" onclick="validarUpload();" />
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12">Tarifas</div>
        <hr />
        <div class="col-md-6">Tarifa ID</div>
        <div class="col-md-6">Descripcion</div>
        <hr />
        <div class="">
            <div class="col-md-6 celD">10284</div>
            <div class="col-md-6 celD">Bed and breakfast</div>
        </div>
        <div class="">
            <div class="col-md-6 celD">10285</div>
            <div class="col-md-6 celD">No Reembolsable</div>
        </div>
    </div>
    <div>
        Connect..1
        @Html.TextAreaFor(model => model.texto, 7, 63, new { @title = "Texto", @class = "form-control textarea-wide" })
    </div>
</div>

ReservasWeb/Views/ChannelManager/View0.cshtml
@model ReservasWeb.ViewModels.ChannelViewModel

<!DOCTYPE html>
@{
    Layout = null;
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />

</head>
<body>
    <div>
        Connect..1
        @Html.TextAreaFor(model => model.texto, 7, 63, new { @title = "Texto", @class = "form-control textarea-wide" })
    </div>
</body>
</html>

ReservasWeb/Views/ChannelManager/elegirTiposHabitaciones.cshtml
@model ReservasWeb.ViewModels.Channel.listadoChannelTipoHabViewModel

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">

    $(function () {
        $('.disponibleAbonoHabitacionSwitch').change(function () {
                var idTipoHabitacion = $(this).data('id');
                var checkbox = $(this);
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: '/ChannelManager/ActivarLink/',
                    dataType: 'JSON',
                    data: {
                        id: idTipoHabitacion,
                        disponible: this.checked
                    },
                    success: function (resdata) {
                        if (resdata["Resultado"] != "ok") {
                            setTimeout(
                              function () {
                                  checkbox.prop('checked', false);
                              }, 500);

                        } else {
                            
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                    }
                });
            //}

        });
    });


</script>

<div class="BarraAdmTopFlotante">
    <div class="container">
        <div class="barraMensajes">
            <span class="MensajeProcesando" id="Procesando" style="display:none;">Procesando...</span>


        </div>
    </div>
</div>

<div class="container">
@using (Html.BeginForm("guardarTiposHabitaciones", "ChannelManager", FormMethod.Post, new { id = "frmCombina" }))
            {
    <center><h2>Habitaciones</h2></center><br />

    <p class="controlesHabitaciones">
        <br />
        <br />
        <input type="submit" class="btn-default" />
        <br />
        <br />

        <div class="planContratado">
            <div><b>Plan Ilimitado habitaciones</b></div>
            <div>(Habitaciones disponibles <span id="cantidadDisponiblesWebMostrador"> Infinito</span>)</div>
        </div>

    </p>
    <table class="table">
        <tr>
            <th class="col-md-2 text-center">

                Activar / Desactivar<br />Portales
            </th>
            <th>Tipo Habitacion</th>
            <th>Estado</th>
            <th>Cantidad Locales</th>
            <th>Cantidad Externas</th>
            <th>Tipo de Habitacion ROOM CLOUD</th>
        </tr>

        @{ 
            int i = -1;
        }
        @foreach (ReservasWeb.Models.TiposHabitacione item in Model.listado)
            {
                i++;
            <tr>
                <td class="col-md-2 text-center">
                    <!-- Rounded switch -->
                    <label class="switch">
                        <input type="checkbox" class="disponibleAbonoHabitacionSwitch" data-id="@(item.idTipoHabitacion)" @(item.idLink.HasValue && item.idLink.Value !=0 ? "checked" : "") />
                        <span class="slider round"></span>
                    </label>

                </td>
                <td>@item.nombreEs</td>
                <td>
                    Status
                </td>
                <td>@item.Habitaciones.Count()</td>
                <td>0</td>
                <td style="font-size:15px;">
                    Codigo: @(item.idLink.HasValue && item.idLink.Value != 0 ? item.idLink.Value.ToString() : "NO LINKEADO")
                    @Html.DropDownListFor(model => model.linkList[i], Model.comboTipoHab, new { @class = "form-control" })
                   
                </td>
            </tr>
        }

    </table>
    }
</div>