ReservasWeb/Models/TarifasPorDia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifasPorDia
    {
        public System.DateTime fecha { get; set; }
        public int idTipoHabitacion { get; set; }
        public int idCanal { get; set; }
        public int idAlojamiento { get; set; }
        public decimal tarifaBase { get; set; }
        public Nullable<decimal> descuentoPorPax { get; set; }
        public Nullable<decimal> adicionalCuna { get; set; }
        public Nullable<decimal> adicionalMenor { get; set; }
        public Nullable<decimal> adicionalAdulto { get; set; }
        public Nullable<int> estadiaMinima { get; set; }
        public Nullable<bool> permiteIngreso { get; set; }
        public Nullable<bool> permiteEgreso { get; set; }
        public Nullable<bool> aceptaMenores { get; set; }
        public Nullable<bool> abierta { get; set; }
        public Nullable<int> disponibilidadCanal { get; set; }
        public Nullable<int> idCondReserva { get; set; }
        public int idTarifaPorDia { get; set; }
    
        public virtual CanalesPorAlojamiento CanalesPorAlojamiento { get; set; }
        public virtual CondReserva CondReserva { get; set; }
        public virtual TiposHabitacione TiposHabitacione { get; set; }
    }
}

ReservasWeb/Controllers/TarifasPorDiaController.cs
using ReservasWeb.Authorize;
using ReservasWeb.Models;
using ReservasWeb.Services;
using ReservasWeb.Utils;
using ReservasWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ReservasWeb.Controllers
{
    [RequiereLogin]
    public class TarifasPorDiaController : BaseController
    {
        // GET: TiposHabitacion
        public async Task<ActionResult> Index(string resultado, string idTipoHabitacion = "0", string idCanal = "0", string idCondicionReserva = null, string fechaDesde = null)
        {
            chequearPermisos(9,0);
            //EdicionTarifasPorDiaViewModel vm = await this.ObtenerEdicionTarifasPorDiaViewModel(0, 0, null, null, null);
            int idTipoHabitacionInt, idCanalInt, idCondicionReservaInt;
            int? idCondicionReservaIntFinal;
            if (!Int32.TryParse(idTipoHabitacion, out idTipoHabitacionInt))
                idTipoHabitacionInt = 0;
            if (!Int32.TryParse(idCanal, out idCanalInt))
                idCanalInt = 0;
            if (!Int32.TryParse(idCondicionReserva, out idCondicionReservaInt) || idCondicionReserva == "0" || idCondicionReserva == "-1")
                idCondicionReservaIntFinal = null;
            else
                idCondicionReservaIntFinal = idCondicionReservaInt;
            
            EdicionTarifasPorDiaViewModel vm = await this.ObtenerEdicionTarifasPorDiaViewModel(idTipoHabitacionInt, idCanalInt, idCondicionReservaIntFinal, fechaDesde, null);
            vm.ProcesarResultado(resultado);

            //// T A R I F A S   B A S E S
            CanalesService canalService = new CanalesService(this.db);
            List<Canale> canalesLista = new List<Canale>();
            canalesLista = canalService.getCanalesDeAlojamiento();

            CondicionesReservaService condicionesReservaSV = new CondicionesReservaService(this.db);

            List<CondReserva> condicionesReservas = condicionesReservaSV.getCondicionesReservaListadoAbm();

            vm.tarifaBaseListado = new List<TarifaBaseViewModel>();
          
            CondReserva condicion = null;
            vm.condicionesReservaListado = new List<SelectListItem>();
            string condicionId, condicionNombre;
            bool selected = false;
            for (int x = -1; x < condicionesReservas.Count(); x++)
            {
                if (x >= 0)
                {
                    condicion = condicionesReservas.ElementAt(x);
                    condicionId = condicion.idCondReserva.ToString();
                    condicionNombre = condicion.nombreEs;
                    selected = false;
                }
                else
                {
                    condicionId = x.ToString();
                    condicionNombre = "Sin condiciones";
                    selected = true;
                }

                vm.condicionesReservaListado.Add(new SelectListItem { Value = condicionId, Text = condicionNombre, Selected = selected });

                //tarifaBaseListado = new List<TarifaBaseViewModel>();
                TarifasBaseService tarifasBaseService = new TarifasBaseService(this.db);
                TarifaBaseViewModel tarifaBaseViewModel;
                TarifasBase tarifaBase;
                for (int i = 0; i < canalesLista.Count(); i++)
                {

                    tarifaBaseViewModel = new TarifaBaseViewModel();
                    tarifaBaseViewModel.idTipoHabitacion = vm.idTipoHabitacion;
                    tarifaBaseViewModel.idCanal = canalesLista.ElementAt(i).idCanal;
                    tarifaBaseViewModel.nombreCanalEs = canalesLista.ElementAt(i).nombreEs;
                    tarifaBaseViewModel.nombreCanalEn = canalesLista.ElementAt(i).nombreEn;
                    tarifaBaseViewModel.nombreCanalPt = canalesLista.ElementAt(i).nombrePt;


                    tarifaBase = tarifasBaseService.get(vm.idTipoHabitacion, canalesLista.ElementAt(i).idCanal, Convert.ToInt32(condicionId));
                    if (tarifaBase != null)
                    {
                        tarifaBaseViewModel.tarifaLunes = tarifaBase.tarifaLunes == 0 ? "" : Convert.ToString(tarifaBase.tarifaLunes, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaMartes = tarifaBase.tarifaMartes == 0 ? "" : Convert.ToString(tarifaBase.tarifaMartes, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaMiercoles = tarifaBase.tarifaMiercoles == 0 ? "" : Convert.ToString(tarifaBase.tarifaMiercoles, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaJueves = tarifaBase.tarifaJueves == 0 ? "" : Convert.ToString(tarifaBase.tarifaJueves, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaViernes = tarifaBase.tarifaViernes == 0 ? "" : Convert.ToString(tarifaBase.tarifaViernes, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaSabado = tarifaBase.tarifaSabado == 0 ? "" : Convert.ToString(tarifaBase.tarifaSabado, new CultureInfo("en-US"));
                        tarifaBaseViewModel.tarifaDomingo = tarifaBase.tarifaDomingo == 0 ? "" : Convert.ToString(tarifaBase.tarifaDomingo, new CultureInfo("en-US"));
                        tarifaBaseViewModel.descuentoPax = tarifaBase.descuentoPax == 0 ? "" : Convert.ToString(tarifaBase.descuentoPax, new CultureInfo("en-US"));
                        tarifaBaseViewModel.adicionalCuna = tarifaBase.adicionalCuna == 0 ? "" : Convert.ToString(tarifaBase.adicionalCuna, new CultureInfo("en-US"));
                        tarifaBaseViewModel.adicionalMenor = tarifaBase.adicionalMenor == 0 ? "" : Convert.ToString(tarifaBase.adicionalMenor, new CultureInfo("en-US"));
                        tarifaBaseViewModel.adicionalAdulto = tarifaBase.adicionalAdulto == 0 ? "" : Convert.ToString(tarifaBase.adicionalAdulto, new CultureInfo("en-US"));
                        tarifaBaseViewModel.estadiaMinima = tarifaBase.estadiaMinima == 0 ? "" : Convert.ToString(tarifaBase.estadiaMinima, new CultureInfo("en-US"));
                        tarifaBaseViewModel.permiteEgreso = Convert.ToBoolean(tarifaBase.permiteEgreso);
                        tarifaBaseViewModel.permiteIngreso = Convert.ToBoolean(tarifaBase.permiteIngreso);
                        tarifaBaseViewModel.aceptaMenores = Convert.ToBoolean(tarifaBase.aceptaMenores);
                        tarifaBaseViewModel.abierta = Convert.ToBoolean(tarifaBase.abierta);
                        //tarifaBaseViewModel.permiteEgreso = true;
                        //tarifaBaseViewModel.permiteIngreso = true;
                        //tarifaBaseViewModel.aceptaMenores = true;
                        //tarifaBaseViewModel.abierta = true;
                    }
                    else
                    {
                        //    tarifaBaseViewModel.tarifaLunes = "0";
                        //    tarifaBaseViewModel.tarifaMartes = "0";
                        //    tarifaBaseViewModel.tarifaMiercoles = "0";
                        //    tarifaBaseViewModel.tarifaJueves = "0";
                        //    tarifaBaseViewModel.tarifaViernes = "0";
                        //    tarifaBaseViewModel.tarifaSabado = "0";
                        //    tarifaBaseViewModel.tarifaDomingo = "0";
                        //    tarifaBaseViewModel.descuentoPax = "0";
                        //    tarifaBaseViewModel.adicionalCuna = "0";
                        //    tarifaBaseViewModel.adicionalMenor = "0";
                        //    tarifaBaseViewModel.adicionalAdulto = "0";
                        tarifaBaseViewModel.permiteEgreso = true;
                        tarifaBaseViewModel.permiteIngreso = true;
                        tarifaBaseViewModel.aceptaMenores = true;
                        tarifaBaseViewModel.estadiaMinima = "1";


                        //si no tiene condicion y es Canal Web o Mostrador, entonces abierto por default
                        if (condicionId == "-1" && (canalesLista.ElementAt(i).idCanal == Convert.ToInt32(ConfigurationManager.AppSettings["idCanalWeb"]) || canalesLista.ElementAt(i).idCanal == Convert.ToInt32(ConfigurationManager.AppSettings["idCanalMostrador"])))
                            tarifaBaseViewModel.abierta = true;
                    }

                    vm.tarifaBaseListado.Add(tarifaBaseViewModel);


                }

                //vm.tarifaBaseListado.Add(Convert.ToInt32(condicionId), tarifaBaseListado);

            }


            ////
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Index(EdicionTarifasPorDiaViewModel vm)
        public ActionResult Index(EdicionTarifasPorDiaViewModel vm)        
        {
            chequearPermisos(9,0);
            string resultado = "ok";
            try
            {
                if (ModelState.IsValid)
                {
                    string[] diasEditados = vm.diasEditados.Split(',');
                    TarifaPorDiaViewModel tarifaPorDiaVM;
                    TarifasPorDiaService sv = new TarifasPorDiaService(this.db);
                    for (int i = 1; i < diasEditados.Length-1; i++)
                    {
                        tarifaPorDiaVM = vm.tarifaPorDiaListado.ElementAt(Int32.Parse(diasEditados[i]));
                        sv.editar(tarifaPorDiaVM);
                    }



                    //vm = await this.ObtenerEdicionTarifasPorDiaViewModel(vm.idTipoHabitacion, vm.idCanal, vm.idCondicionReserva, vm.tarifaPorDiaListado[0].fecha.ToString("dd/MM/yyyy"), null);
                    //vm.ProcesarResultado(resultado);
                    //return View(vm);

ReservasWeb/Views/TarifasPorDia/Index.cshtml
@model ReservasWeb.ViewModels.EdicionTarifasPorDiaViewModel

@{
    ViewBag.Title = "Index";
}

<script type="text/javascript">

    var actualizando = false;

    $(document).ready(function () {
        $("#idTipoHabitacion").change(function () {
            actualizarTarifasPorDiaListado()
        });
        $("#idCanal").change(function () {
            actualizarTarifasPorDiaListado()
        });
        $("#idCondicionReserva").change(function () {
            actualizarTarifasPorDiaListado()
        });
    });

    function actualizarTarifasPorDiaListado(dias) {
        actualizando = true;
        dias = typeof dias !== 'undefined' ? dias : 0;
        var idHabitcion = $("#idTipoHabitacion").val();
        var idCanal = $("#idCanal").val();
        var idCondicionReserva = $("#idCondicionReserva").val();
        if (idCondicionReserva == "-1")
            idCondicionReserva = null;
        var fechaDesde = $("#fechaDesde").val();

        var fechaDesdeSplit = $("#fechaDesde").val().split("/");
        var date = new Date(fechaDesdeSplit[2], fechaDesdeSplit[1] - 1, fechaDesdeSplit[0]);
        if (!isNaN(date.getTime())) {
            date.setDate(date.getDate() + dias);
            fechaDesde = $.datepicker.formatDate('dd/mm/yy', date);
        }
        
        $("#tarifaCargando").fadeIn("slow");
        $("#TarifaPorDiaListadoDiv").load('@(Url.Action("TarifasPorDiaListado", "TarifasPorDia", null, null))?idHabitcion=' + idHabitcion + '&idCanal=' + idCanal + '&idCondicionReserva=' + idCondicionReserva + '&fechaDesde=' + fechaDesde,
            function () {
                $("#tarifaCargando").fadeOut("slow");
                actualizando = false;
            }
        );
    }

    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
    
</script>

@using (Html.BeginForm())
    {
    @Html.AntiForgeryToken()

<div class="BarraAdmTopFlotante">
    <div class="container">
        <div class="barraMensajes">
            <span class="MensajeProcesando" id="Procesando" style="display:none;">Procesando...</span>

            @if (Model.MensajeExito != null)
            {
                <span class="MensajeOk">@Model.MensajeExito</span>
            }
            else if (Model.MensajeError != null)
            {
                <span class="MensajeError">@Model.MensajeError</span>
            }
            <input id="guardarBoton" disabled="disabled" type="submit" value="Guardar Cambios" class="btn btn-normal btnFrmGeneral" onclick="procesando();" data-toggle="tooltip" data-placement="bottom" title="Se podrá Guardar Cambios, cuando modifique al menos un dato en la grilla." />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-primary btnFrmGeneral" })            
        </div>        
        
    </div>
</div>

    <div class="container">

        <center><h2>Tarifas y Restricciones por Día</h2></center>

    @if (Model.tiposHabitacion != null && Model.tiposHabitacion.Count() > 0)
    {
        <p>
            @Html.ActionLink("Carga Masiva", "EditarMasivo", null, new { @class = "modal-link btn btn-success" })
        </p>

        <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row filtrosTarifasPorDia">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.tiposHabitacion, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.idTipoHabitacion, Model.tiposHabitacion, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group col-md-3">
                    @Html.LabelFor(model => model.canales, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.idCanal, Model.canales, new { @class = "form-control" })
                    </div>
                </div>
                
                <div class="form-group col-md-5">
                    @Html.LabelFor(model => model.condicionesReservas, htmlAttributes: new { @class = "control-label col-md-5" })
                    <div class="col-md-7">
                        @Html.DropDownListFor(model => model.idCondicionReserva, Model.condicionesReservas, new { @class = "form-control" })
                    </div>
                </div>                
            </div>

            <div class="row" id="TarifaPorDiaListadoDiv">
                @Html.Partial("TarifaPorDiaListado", Model)
            </div>       

            @*<div class="row" id="TarifaBaseListadoDiv">
                @Html.Partial("TarifaBaseListado", Model)
            </div>*@

     
        </div>
    }
    else
    {
        <p>
            <div class="alert alert-warning alert-dismissible fade in" role="alert">
                Es necesario cargar Tipos de Habitación en el sistema.
            </div>
        </p>    
    }
</div>

    }
    