ReservasWeb/Controllers/TiposHabitacionController.cs
using ReservasWeb.Authorize;
using ReservasWeb.Models;
using ReservasWeb.Services;
using ReservasWeb.Utils;
using ReservasWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservasWeb.Controllers
{
    [RequiereLogin]
    public class TiposHabitacionController : BaseController
    {
        // GET: TiposHabitacion
        public ActionResult Index(string resultado)
        {
            chequearPermisos(4,0);            
            ListadoTiposHabitacionViewModel vm = new ListadoTiposHabitacionViewModel();
            TiposHabitacionService svTip = new TiposHabitacionService(this.db);
            vm.listado = svTip.getTiposHabitacionPorAlojamiento();
            vm.ProcesarResultado(resultado);
            return View(vm);
        }

        public ActionResult Crear()
        {
            chequearPermisos(4, 1);
            CreacionTipoHabitacionViewModel vm = new CreacionTipoHabitacionViewModel();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Crear(CreacionTipoHabitacionViewModel vm)
        {
            string resultado = "error";
            int idTipoHabitacion = 0;
            try
            {
                if (ModelState.IsValid)
                {
                    TiposHabitacionService svTip = new TiposHabitacionService(this.db);                    
                    idTipoHabitacion = svTip.Crear(vm);
                    
                    TarifasBaseService tarifasBaseService = new TarifasBaseService(this.db);
                    CondicionesReservaService condicionesReservaSV = new CondicionesReservaService(this.db);
                    CanalesService canalService = new CanalesService(this.db);

                    List<Canale> canalesLista = new List<Canale>();
                    canalesLista = canalService.getCanalesDeAlojamiento();
                    List<CondReserva> condicionesReservas = new List<CondReserva>();
                    condicionesReservas = condicionesReservaSV.getCondicionesReservaListadoAbm();

                    for (int x = -1; x < condicionesReservas.Count(); x++)
                    {
                        for (int i = 0; i < canalesLista.Count(); i++)
                        {
                            TarifasBase tarifaBase = new TarifasBase();
                            tarifaBase.abierta = true;
                            tarifaBase.aceptaMenores = true;
                            tarifaBase.adicionalAdulto = 0;
                            tarifaBase.adicionalCuna = 0;
                            tarifaBase.adicionalMenor = 0;
                            tarifaBase.descuentoPax = 0;
                            tarifaBase.disponibilidadCanal = 1;
                            tarifaBase.estadiaMinima = 1;
                            tarifaBase.idAlojamiento = BaseService.getIdAlojamiento();
                            tarifaBase.idCanal = canalesLista[i].idCanal;
                            if (x >= 0)
                            {
                                tarifaBase.idCondReserva = condicionesReservas[x].idCondReserva;
                            }
                            tarifaBase.idTipoHabitacion = idTipoHabitacion;
                            tarifaBase.permiteEgreso = true;
                            tarifaBase.permiteIngreso = true;
                            tarifaBase.tarifaLunes = 0;
                            tarifaBase.tarifaMartes = 0;
                            tarifaBase.tarifaMiercoles = 0;
                            tarifaBase.tarifaJueves = 0;
                            tarifaBase.tarifaViernes = 0;
                            tarifaBase.tarifaSabado = 0;
                            tarifaBase.tarifaDomingo = 0;
                            db.TarifasBases.Add(tarifaBase);
                            db.SaveChanges();
                        }
                    }
                    resultado = "ok";
                }
            }
            catch (Exception)
            {                
            }
            if (idTipoHabitacion > 0)
                return RedirectToAction("Editar", new { id = idTipoHabitacion });
            else
                return RedirectToAction("Index", new { resultado = resultado });
        }

        public ActionResult Editar(int id)
        {
            chequearPermisos(4, 3);
            TiposHabitacionService sv = new TiposHabitacionService(this.db);
            //CondicionesReservaService condicionesReservaSV = new CondicionesReservaService(this.db);
            EdicionTipoHabitacionViewModel vm = sv.getTipoHabitacionEdicion(id);
            if (vm.horaCheckOutTardio == null)
                vm.horaCheckOutTardio = "10:00";
            //vm.plazasSelectList = sv.getComboPlazas(0);
            
            vm.camasSimpleMatrimonialSelectList = sv.getComboCamasSimplesMatrimoniales();
            vm.permiteCamasAdicionalesSelectList = sv.getComboSiNo();
            vm.permiteAdicionalesBebeSelectList = sv.getComboSiNo();
            vm.permiteAdicionalesMenorSelectList = sv.getComboSiNo();
            vm.permiteAdicionalesAdultoSelectList = sv.getComboSiNo();
            vm.camasAdicionalesSelectList = sv.getComboCamasAdicionales(0);

            //CanalesService canalService = new CanalesService(this.db);
            //List<Canale> canalesLista = new List<Canale>();
            //canalesLista = canalService.getCanalesDeAlojamiento();



            //List<CondReserva> condicionesReservas = condicionesReservaSV.getCondicionesReservaListadoAbm();

            ////vm.tarifaBaseListado = new Dictionary<int, List<TarifaBaseViewModel>>();
            //vm.tarifaBaseListado = new List<TarifaBaseViewModel>();
            ////vm.tarifaBaseListado.Add(con)
            ////CondReserva condicion;
            ////foreach(condicion in condicionesReservas)
            ////{

            ////}

            ////List<TarifaBaseViewModel> tarifaBaseListado;
            ////foreach (CondReserva condicion in condicionesReservaSV.getCondicionesReservaListadoAbm())
            //CondReserva condicion = null;
            //vm.condicionesReservaListado = new List<SelectListItem>();
            //string condicionId, condicionNombre;
            //bool selected = false;
            ////vm.condicionesReservaListado.Add(new SelectListItem { Value = "-1", Text = "Sin condiciones", Selected = true });
            //for (int x = -1; x < condicionesReservas.Count(); x++)
            //{
            //    if (x >= 0) {
            //        condicion = condicionesReservas.ElementAt(x);
            //        condicionId = condicion.idCondReserva.ToString();
            //        condicionNombre = condicion.nombreEs;
            //        selected = false;
            //    }
            //    else
            //    {
            //        condicionId = x.ToString();
            //        condicionNombre = "Sin condiciones";
            //        selected = true;
            //    }

            //    vm.condicionesReservaListado.Add(new SelectListItem { Value = condicionId, Text = condicionNombre, Selected = selected });

            //    //tarifaBaseListado = new List<TarifaBaseViewModel>();
            //    TarifasBaseService tarifasBaseService = new TarifasBaseService(this.db);
            //    TarifaBaseViewModel tarifaBaseViewModel;
            //    TarifasBase tarifaBase;
            //    for (int i = 0; i < canalesLista.Count(); i++)
            //    {

            //        tarifaBaseViewModel = new TarifaBaseViewModel();
            //        tarifaBaseViewModel.idTipoHabitacion = vm.idTipoHabitacion;
            //        tarifaBaseViewModel.idCanal = canalesLista.ElementAt(i).idCanal;
            //        tarifaBaseViewModel.nombreCanalEs = canalesLista.ElementAt(i).nombreEs;
            //        tarifaBaseViewModel.nombreCanalEn = canalesLista.ElementAt(i).nombreEn;
            //        tarifaBaseViewModel.nombreCanalPt = canalesLista.ElementAt(i).nombrePt;


            //        tarifaBase = tarifasBaseService.get(vm.idTipoHabitacion, canalesLista.ElementAt(i).idCanal, Convert.ToInt32(condicionId));
            //        if (tarifaBase != null)
            //        {
            //            tarifaBaseViewModel.tarifaLunes = tarifaBase.tarifaLunes == 0 ? "" : Convert.ToString(tarifaBase.tarifaLunes, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaMartes = tarifaBase.tarifaMartes == 0 ? "" : Convert.ToString(tarifaBase.tarifaMartes, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaMiercoles = tarifaBase.tarifaMiercoles == 0 ? "" : Convert.ToString(tarifaBase.tarifaMiercoles, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaJueves = tarifaBase.tarifaJueves == 0 ? "" : Convert.ToString(tarifaBase.tarifaJueves, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaViernes = tarifaBase.tarifaViernes == 0 ? "" : Convert.ToString(tarifaBase.tarifaViernes, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaSabado = tarifaBase.tarifaSabado == 0 ? "" : Convert.ToString(tarifaBase.tarifaSabado, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.tarifaDomingo = tarifaBase.tarifaDomingo == 0 ? "" : Convert.ToString(tarifaBase.tarifaDomingo, new CultureInfo("en-US"));
            //            tarifaBaseViewModel.descuentoPax = tarifaBase.descuentoPax == 0 ? "" : Convert.ToString(tarifaBase.descuentoPax, new CultureInfo("en-US"));

ReservasWeb/Views/TiposHabitacion/Crear.cshtml
@model ReservasWeb.ViewModels.CreacionTipoHabitacionViewModel

    @{
    ViewBag.Title = "Create";

    Layout = "";

    AjaxOptions options = new AjaxOptions();
    options.HttpMethod = "POST";
    options.Url = Url.Action("Create", "Clientes");
    options.UpdateTargetId = "modal-container";
    options.InsertionMode = InsertionMode.Replace;
    options.OnSuccess = "onSuccess";
}

<script type="text/javascript">
    //$.validator.setDefaults({ ignore: ".hidden .form-control, .ignore" });
    $.validator.unobtrusive.parse($("form"));
</script>

<div class="modal-dialog" role="document">
    <div class="modal-content">
        @using (Ajax.BeginForm("Crear", "TiposHabitacion", null, options, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()

            <div class="modal-header">
                <center><h2>Nuevo Tipo de Habitación</h2></center>
            </div>
            <div class="modal-body">
                <div class="row">

                    <div class="col-md-12">

                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(model => model.nombre, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div class="modal-footer">

                <div class="row">
                    &nbsp;
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <input type="submit" value="Crear" class="btn btn-success" />
                    </div>
                </div>

            </div>
        }
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#approve-btn').click(function () {
            $('#modal-container').modal('hide');
        });
    });

    var onSuccess = function (result) {
        if (result.url) {
            // if the server returned a JSON object containing an url
            // property we redirect the browser to that url
            window.location.href = result.url;
        }
    }
</script>

ReservasWeb/Views/TiposHabitacion/Index.cshtml
@model ReservasWeb.ViewModels.ListadoTiposHabitacionViewModel

@{
    ViewBag.Title = "Index";
}

    <script type="text/javascript">

        //function eliminar(idTipoHabitacion) {
        //    var borra = confirm("¿Está seguro que desea eliminar este Tipo de Habitación?")
        //    if (borra) {
        //        //var idTipoHabitacion = $(this).attr('data-id');
        //        $.ajax({
        //            cache: false,
        //            type: "POST",
        //            url: '/TiposHabitacion/Eliminar/',
        //            dataType: 'JSON',
        //            data: { id: idTipoHabitacion },
        //            success: function (resdata) {
        //                $('#ContenedorTiposHabitacion #tipoHabitacionItem-' + idTipoHabitacion).fadeOut(500);
        //            },
        //            error: function (xhr, ajaxOptions, thrownError) {
        //                alert("tiro Error");
        //            }
        //        });
        //    }
        //}

    </script>

<div class="BarraAdmTopFlotante">
    <div class="container">
        <div class="barraMensajes">
            <span class="MensajeProcesando" id="Procesando" style="display:none;">Procesando...</span>

            @if (Model.MensajeExito != null)
            {
                <span class="MensajeOk">@Model.MensajeExito</span>
            }
            else if (Model.MensajeError != null)
            {
                <span class="MensajeError">@Model.MensajeError</span>
            }            
        </div>
    </div>
</div>

    <div class="container">
        <div class="col-md-12">
            <center><h2>Tipos de Habitación</h2></center>

            <p>
                @Html.ActionLink("Nuevo +", "Crear", null, new { @class = "modal-link btn btn-success" })
            </p>
            <table class="table" id="ContenedorTiposHabitacion">
                <tr>
                    <th class="col-md-3">Nombre</th>
                    <th>Plazas</th>
                    <th>Cama Matrimonial</th>
                    <th>Camas Simples</th>
                    <th>Camas Adicionales</th>
                    <th></th>
                </tr>

                @foreach (var item in Model.listado)
                {
                    bool datosIncompletos = item.plazas == 0 || item.TarifasBases.Count() == 0 || item.plazas == null;
                    <tr id="tipoHabitacionItem-@item.idTipoHabitacion" class="@(datosIncompletos ? "danger" : "")">
                        <td class="col-md-3">@item.nombreEs</td>
                        @if (datosIncompletos)
                        {
                            <td colspan="4" class="text-danger errorEnTabla">Datos incompletos, cargue Plazas por favor</td>
                        }
                        else
                        {
                            <td>@item.plazas</td>
                            <td>@item.camaMatrimonial</td>
                            <td>@item.camasSimples</td>
                            <td>@item.camasAdicionales</td>
                        }                        
                        <td>
                            @Html.ActionLink("Editar", "Editar", new { id = item.idTipoHabitacion }) |
                            @*@Html.ActionLink("Eliminar", "Eliminar", new { id = item.idTipoHabitacion, @class = "Eliminar", @data_id = item.idTipoHabitacion })*@
                            @*@Html.ActionLink("Eliminar", "Eliminar", null, new { @class = "Eliminar", @data_id = item.idTipoHabitacion })*@
                            @*<a href="javascript:void(0);" onclick="eliminar(@item.idTipoHabitacion);" data-id="@item.idTipoHabitacion" class="Eliminar"> Eliminar</a>*@
                            @*<a href="javascript:void(0);" onclick="eliminar(@item.idTipoHabitacion);" class="Eliminar"> Eliminar</a>*@
                            @Html.ActionLink("Eliminar", "Eliminar", new { id = item.idTipoHabitacion }, new { onclick = "return confirm('¿Está seguro que desea eliminar \"" + @item.nombreEs + "\"?');" })                            
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>

